# Generated by Django 4.2.3 on 2023-12-12 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='cvv',
            new_name='CVV',
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(max_length=5),
        ),
    ]
